python src/learning/apply_model.py --outdir apply.reduced/Gasperini/ --modelfile run.reduced/reduced.save.0.json --scalerfile run.reduced/reduced.scaler.0.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Gasperini/ --modelfile run.reduced/reduced.save.1.json --scalerfile run.reduced/reduced.scaler.1.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Gasperini/ --modelfile run.reduced/reduced.save.2.json --scalerfile run.reduced/reduced.scaler.2.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Gasperini/ --modelfile run.reduced/reduced.save.3.json --scalerfile run.reduced/reduced.scaler.3.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.target.txt

python src/learning/apply_model.py --outdir apply.reduced/Gasperini.atleast1sig/ --modelfile run.reduced/reduced.save.0.json --scalerfile run.reduced/reduced.scaler.0.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.atleast1sig.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Gasperini.atleast1sig/ --modelfile run.reduced/reduced.save.1.json --scalerfile run.reduced/reduced.scaler.1.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.atleast1sig.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Gasperini.atleast1sig/ --modelfile run.reduced/reduced.save.2.json --scalerfile run.reduced/reduced.scaler.2.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.atleast1sig.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Gasperini.atleast1sig/ --modelfile run.reduced/reduced.save.3.json --scalerfile run.reduced/reduced.scaler.3.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.atleast1sig.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.dropna.atleast1sig.target.txt




python src/learning/apply_model.py --outdir apply.reduced/Fulco/ --modelfile run.reduced/reduced.save.0.json --scalerfile run.reduced/reduced.scaler.0.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Fulco/ --modelfile run.reduced/reduced.save.1.json --scalerfile run.reduced/reduced.scaler.1.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Fulco/ --modelfile run.reduced/reduced.save.2.json --scalerfile run.reduced/reduced.scaler.2.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Fulco/ --modelfile run.reduced/reduced.save.3.json --scalerfile run.reduced/reduced.scaler.3.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.target.txt

python src/learning/apply_model.py --outdir apply.reduced/Fulco.atleast1sig/ --modelfile run.reduced/reduced.save.0.json --scalerfile run.reduced/reduced.scaler.0.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.atleast1sig.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Fulco.atleast1sig/ --modelfile run.reduced/reduced.save.1.json --scalerfile run.reduced/reduced.scaler.1.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.atleast1sig.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Fulco.atleast1sig/ --modelfile run.reduced/reduced.save.2.json --scalerfile run.reduced/reduced.scaler.2.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.atleast1sig.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Fulco.atleast1sig/ --modelfile run.reduced/reduced.save.3.json --scalerfile run.reduced/reduced.scaler.3.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.atleast1sig.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.atleast1sig.target.txt



python src/learning/apply_model.py --outdir apply.reduced/Schraivogel/ --modelfile run.reduced/reduced.save.0.json --scalerfile run.reduced/reduced.scaler.0.gz  --features data/Schraivogel/CRISPR.ABC.TF.test.txt --targets data/Schraivogel/CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Schraivogel/ --modelfile run.reduced/reduced.save.1.json --scalerfile run.reduced/reduced.scaler.1.gz  --features data/Schraivogel/CRISPR.ABC.TF.test.txt --targets data/Schraivogel/CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Schraivogel/ --modelfile run.reduced/reduced.save.2.json --scalerfile run.reduced/reduced.scaler.2.gz  --features data/Schraivogel/CRISPR.ABC.TF.test.txt --targets data/Schraivogel/CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Schraivogel/ --modelfile run.reduced/reduced.save.3.json --scalerfile run.reduced/reduced.scaler.3.gz  --features data/Schraivogel/CRISPR.ABC.TF.test.txt --targets data/Schraivogel/CRISPR.ABC.TF.test.target.txt

python src/learning/apply_model.py --outdir apply.reduced/Schraivogel.atleast1sig/ --modelfile run.reduced/reduced.save.0.json --scalerfile run.reduced/reduced.scaler.0.gz  --features data/Schraivogel/CRISPR.ABC.TF.test.atleast1sig.txt --targets data/Schraivogel/CRISPR.ABC.TF.test.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Schraivogel.atleast1sig/ --modelfile run.reduced/reduced.save.1.json --scalerfile run.reduced/reduced.scaler.1.gz  --features data/Schraivogel/CRISPR.ABC.TF.test.atleast1sig.txt --targets data/Schraivogel/CRISPR.ABC.TF.test.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Schraivogel.atleast1sig/ --modelfile run.reduced/reduced.save.2.json --scalerfile run.reduced/reduced.scaler.2.gz  --features data/Schraivogel/CRISPR.ABC.TF.test.atleast1sig.txt --targets data/Schraivogel/CRISPR.ABC.TF.test.atleast1sig.target.txt
python src/learning/apply_model.py --outdir apply.reduced/Schraivogel.atleast1sig/ --modelfile run.reduced/reduced.save.3.json --scalerfile run.reduced/reduced.scaler.3.gz  --features data/Schraivogel/CRISPR.ABC.TF.test.atleast1sig.txt --targets data/Schraivogel/CRISPR.ABC.TF.test.atleast1sig.target.txt


