python src/learning/apply_model.py --outdir apply.all/Gasperini/ --modelfile run.all/all.2pass.save.0.json --scalerfile run.all/all.2pass.scaler.0.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.target.txt
python src/learning/apply_model.py --outdir apply.all/Gasperini/ --modelfile run.all/all.2pass.save.1.json --scalerfile run.all/all.2pass.scaler.1.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.target.txt
python src/learning/apply_model.py --outdir apply.all/Gasperini/ --modelfile run.all/all.2pass.save.2.json --scalerfile run.all/all.2pass.scaler.2.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.target.txt
python src/learning/apply_model.py --outdir apply.all/Gasperini/ --modelfile run.all/all.2pass.save.3.json --scalerfile run.all/all.2pass.scaler.3.gz  --features data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.txt --targets data/Gasperini/Gasperini2019.at_scale.ABC.TF.erole.grouped.test.target.txt


python src/learning/apply_model.py --outdir apply.all/Fulco/ --modelfile run.all/all.2pass.save.0.json --scalerfile run.all/all.2pass.scaler.0.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.all/Fulco/ --modelfile run.all/all.2pass.save.1.json --scalerfile run.all/all.2pass.scaler.1.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.all/Fulco/ --modelfile run.all/all.2pass.save.2.json --scalerfile run.all/all.2pass.scaler.2.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.target.txt
python src/learning/apply_model.py --outdir apply.all/Fulco/ --modelfile run.all/all.2pass.save.3.json --scalerfile run.all/all.2pass.scaler.3.gz  --features data/Fulco/Fulco2019.CRISPR.ABC.TF.test.txt --targets data/Fulco/Fulco2019.CRISPR.ABC.TF.test.target.txt
