#python src/apply_model.py --dir data/ --outdir applymodel/ --modelfile run.boruta7/boruta7.2pass.save.0.json --scalerfile run.boruta7/boruta7.scaler.0.gz  --features data/Gasperini2019.at_scale.ABC.TF.cobinding.erole.grouped.test.txt --targets data/Gasperini2019.at_scale.ABC.TF.cobinding.erole.grouped.test.target.txt
#python src/apply_model.py --dir data/ --outdir applymodel/ --modelfile run.boruta7/boruta7.2pass.save.1.json --scalerfile run.boruta7/boruta7.scaler.1.gz  --features data/Gasperini2019.at_scale.ABC.TF.cobinding.erole.grouped.test.txt --targets data/Gasperini2019.at_scale.ABC.TF.cobinding.erole.grouped.test.target.txt
#python src/apply_model.py --dir data/ --outdir applymodel/ --modelfile run.boruta7/boruta7.2pass.save.2.json --scalerfile run.boruta7/boruta7.scaler.2.gz  --features data/Gasperini2019.at_scale.ABC.TF.cobinding.erole.grouped.test.txt --targets data/Gasperini2019.at_scale.ABC.TF.cobinding.erole.grouped.test.target.txt
#python src/apply_model.py --dir data/ --outdir applymodel/ --modelfile run.boruta7/boruta7.2pass.save.3.json --scalerfile run.boruta7/boruta7.scaler.3.gz  --features data/Gasperini2019.at_scale.ABC.TF.cobinding.erole.grouped.test.txt --targets data/Gasperini2019.at_scale.ABC.TF.cobinding.erole.grouped.test.target.txt


python src/apply_model.py --dir data/ --outdir applymodel/ --modelfile run.boruta7/boruta7.2pass.save.0.json --scalerfile run.boruta7/boruta7.scaler.0.gz  --features data/Fulco2019.CRISPR.ABC.TF.cobinding.txt --targets data/Fulco2019.CRISPR.ABC.TF.cobinding.target.txt
python src/apply_model.py --dir data/ --outdir applymodel/ --modelfile run.boruta7/boruta7.2pass.save.1.json --scalerfile run.boruta7/boruta7.scaler.1.gz  --features data/Fulco2019.CRISPR.ABC.TF.cobinding.txt --targets data/Fulco2019.CRISPR.ABC.TF.cobinding.target.txt
python src/apply_model.py --dir data/ --outdir applymodel/ --modelfile run.boruta7/boruta7.2pass.save.2.json --scalerfile run.boruta7/boruta7.scaler.2.gz  --features data/Fulco2019.CRISPR.ABC.TF.cobinding.txt --targets data/Fulco2019.CRISPR.ABC.TF.cobinding.target.txt
python src/apply_model.py --dir data/ --outdir applymodel/ --modelfile run.boruta7/boruta7.2pass.save.3.json --scalerfile run.boruta7/boruta7.scaler.3.gz  --features data/Fulco2019.CRISPR.ABC.TF.cobinding.txt --targets data/Fulco2019.CRISPR.ABC.TF.cobinding.target.txt
